// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Infrastructure.Academics.Data;

#nullable disable

namespace School.Infrastructure.Academics.Data.Migrations
{
    [DbContext(typeof(AcademicContext))]
    [Migration("20260922102545_AddQuestionPaperPrintAdjustmentsJson")]
    partial class AddQuestionPaperPrintAdjustmentsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("Class", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModuleHead")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tblPermission", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "view_dashboard",
                            IsActive = true,
                            ModuleHead = "Dashboard",
                            Name = "View Dashboard",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            Code = "view_classes",
                            IsActive = true,
                            ModuleHead = "Classes",
                            Name = "View Classes",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            Code = "create_class",
                            IsActive = true,
                            ModuleHead = "Classes",
                            Name = "Create Class",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4,
                            Code = "edit_class",
                            IsActive = true,
                            ModuleHead = "Classes",
                            Name = "Edit Class",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5,
                            Code = "delete_class",
                            IsActive = true,
                            ModuleHead = "Classes",
                            Name = "Delete Class",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = 6,
                            Code = "view_subjects",
                            IsActive = true,
                            ModuleHead = "Subjects",
                            Name = "View Subjects",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = 7,
                            Code = "create_subject",
                            IsActive = true,
                            ModuleHead = "Subjects",
                            Name = "Create Subject",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = 8,
                            Code = "edit_subject",
                            IsActive = true,
                            ModuleHead = "Subjects",
                            Name = "Edit Subject",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = 9,
                            Code = "delete_subject",
                            IsActive = true,
                            ModuleHead = "Subjects",
                            Name = "Delete Subject",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = 10,
                            Code = "view_chapters",
                            IsActive = true,
                            ModuleHead = "Chapters",
                            Name = "View Chapters",
                            SortOrder = 100
                        },
                        new
                        {
                            Id = 11,
                            Code = "create_chapter",
                            IsActive = true,
                            ModuleHead = "Chapters",
                            Name = "Create Chapter",
                            SortOrder = 110
                        },
                        new
                        {
                            Id = 12,
                            Code = "edit_chapter",
                            IsActive = true,
                            ModuleHead = "Chapters",
                            Name = "Edit Chapter",
                            SortOrder = 120
                        },
                        new
                        {
                            Id = 13,
                            Code = "delete_chapter",
                            IsActive = true,
                            ModuleHead = "Chapters",
                            Name = "Delete Chapter",
                            SortOrder = 130
                        },
                        new
                        {
                            Id = 14,
                            Code = "view_question_catalog",
                            IsActive = true,
                            ModuleHead = "Question Catalog",
                            Name = "View Question Catalog",
                            SortOrder = 140
                        },
                        new
                        {
                            Id = 15,
                            Code = "create_question",
                            IsActive = true,
                            ModuleHead = "Question Catalog",
                            Name = "Create Question",
                            SortOrder = 150
                        },
                        new
                        {
                            Id = 16,
                            Code = "edit_question",
                            IsActive = true,
                            ModuleHead = "Question Catalog",
                            Name = "Edit Question",
                            SortOrder = 160
                        },
                        new
                        {
                            Id = 17,
                            Code = "delete_question",
                            IsActive = true,
                            ModuleHead = "Question Catalog",
                            Name = "Delete Question",
                            SortOrder = 170
                        },
                        new
                        {
                            Id = 18,
                            Code = "view_exam_titles",
                            IsActive = true,
                            ModuleHead = "Exam Titles",
                            Name = "View Exam Titles",
                            SortOrder = 180
                        },
                        new
                        {
                            Id = 19,
                            Code = "create_exam_title",
                            IsActive = true,
                            ModuleHead = "Exam Titles",
                            Name = "Create Exam Title",
                            SortOrder = 190
                        },
                        new
                        {
                            Id = 20,
                            Code = "edit_exam_title",
                            IsActive = true,
                            ModuleHead = "Exam Titles",
                            Name = "Edit Exam Title",
                            SortOrder = 200
                        },
                        new
                        {
                            Id = 21,
                            Code = "delete_exam_title",
                            IsActive = true,
                            ModuleHead = "Exam Titles",
                            Name = "Delete Exam Title",
                            SortOrder = 210
                        },
                        new
                        {
                            Id = 22,
                            Code = "view_exam_maker",
                            IsActive = true,
                            ModuleHead = "Exam Maker",
                            Name = "View Exam Maker",
                            SortOrder = 220
                        },
                        new
                        {
                            Id = 23,
                            Code = "create_exam_paper",
                            IsActive = true,
                            ModuleHead = "Exam Maker",
                            Name = "Create Exam Paper",
                            SortOrder = 230
                        },
                        new
                        {
                            Id = 24,
                            Code = "edit_exam_paper",
                            IsActive = true,
                            ModuleHead = "Exam Maker",
                            Name = "Edit Exam Paper",
                            SortOrder = 240
                        },
                        new
                        {
                            Id = 25,
                            Code = "delete_exam_paper",
                            IsActive = true,
                            ModuleHead = "Exam Maker",
                            Name = "Delete Exam Paper",
                            SortOrder = 250
                        },
                        new
                        {
                            Id = 26,
                            Code = "view_institute_settings",
                            IsActive = true,
                            ModuleHead = "Institute",
                            Name = "View Institute Settings",
                            SortOrder = 260
                        },
                        new
                        {
                            Id = 27,
                            Code = "edit_institute_settings",
                            IsActive = true,
                            ModuleHead = "Institute",
                            Name = "Edit Institute Settings",
                            SortOrder = 270
                        },
                        new
                        {
                            Id = 28,
                            Code = "view_users",
                            IsActive = true,
                            ModuleHead = "Users",
                            Name = "View Users",
                            SortOrder = 280
                        },
                        new
                        {
                            Id = 29,
                            Code = "create_user",
                            IsActive = true,
                            ModuleHead = "Users",
                            Name = "Create User",
                            SortOrder = 290
                        },
                        new
                        {
                            Id = 30,
                            Code = "edit_user",
                            IsActive = true,
                            ModuleHead = "Users",
                            Name = "Edit User",
                            SortOrder = 300
                        },
                        new
                        {
                            Id = 31,
                            Code = "delete_user",
                            IsActive = true,
                            ModuleHead = "Users",
                            Name = "Deactivate User",
                            SortOrder = 310
                        });
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectName")
                        .IsUnique();

                    b.ToTable("Subject", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AcademicLogin", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicUserRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("tblUserRights", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ClassId", "SubjectId", "ChapterNo")
                        .IsUnique();

                    b.ToTable("Chapters", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.ExamTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamTitle_Title");

                    b.ToTable("ExamTitle", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.InstituteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstituteAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstituteContact")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstituteEmail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstituteLogo")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InstituteName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("InstituteSettings", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McqOpt1")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_1");

                    b.Property<string>("McqOpt2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_2");

                    b.Property<string>("McqOpt3")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_3");

                    b.Property<string>("McqOpt4")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_4");

                    b.Property<string>("StemImage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("QuestionsCatalog", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExamTitleId")
                        .HasColumnType("int");

                    b.Property<string>("ExamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FooterNote")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("HeaderNote")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PaperName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrintAdjustmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SectionMetaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowSectionNames")
                        .HasColumnType("bit");

                    b.Property<string>("SubQuestionNumberingStyle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<bool>("WrapQuestionMarksInParentheses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ExamTitleId");

                    b.HasIndex("SubjectId");

                    b.ToTable("QuestionPaper", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaperQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuestionPaperId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionPaperId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paper_Question");

                    b.HasIndex("QuestionPaperId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paper_QuestionOrder");

                    b.ToTable("QuestionPaperQuestions", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicUserRight", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.Chapter", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicClass", "Class")
                        .WithMany("Chapters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_Class");

                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicSubject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_Subject");

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionCatalog", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Chapter");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaper", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicClass", "Class")
                        .WithMany("QuestionPapers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionPaper_Class");

                    b.HasOne("School.Infrastructure.Academics.Entities.ExamTitle", "ExamTitle")
                        .WithMany("QuestionPapers")
                        .HasForeignKey("ExamTitleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionPaper_ExamTitle");

                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicSubject", "Subject")
                        .WithMany("QuestionPapers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionPaper_Subject");

                    b.Navigation("Class");

                    b.Navigation("ExamTitle");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaperQuestion", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.QuestionCatalog", "Question")
                        .WithMany("QuestionPaperQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QPQ_Question");

                    b.HasOne("School.Infrastructure.Academics.Entities.QuestionPaper", "QuestionPaper")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QPQ_Paper");

                    b.Navigation("Question");

                    b.Navigation("QuestionPaper");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicClass", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("QuestionPapers");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicSubject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("QuestionPapers");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.Chapter", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.ExamTitle", b =>
                {
                    b.Navigation("QuestionPapers");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionCatalog", b =>
                {
                    b.Navigation("QuestionPaperQuestions");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaper", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
