// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Infrastructure.Academics.Data;

#nullable disable

namespace School.Infrastructure.Academics.Data.Migrations
{
    [DbContext(typeof(AcademicContext))]
    [Migration("20260728161527_SetDefaultSchemaDbo")]
    partial class SetDefaultSchemaDbo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("Class", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectName")
                        .IsUnique();

                    b.ToTable("Subject", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AcademicLogin", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ClassId", "SubjectId", "ChapterNo")
                        .IsUnique();

                    b.ToTable("Chapters", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.ExamTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ExamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UX_ExamTitle_Title");

                    b.ToTable("ExamTitle", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.InstituteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstituteAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstituteContact")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstituteEmail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstituteLogo")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InstituteName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("InstituteSettings", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McqOpt1")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_1");

                    b.Property<string>("McqOpt2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_2");

                    b.Property<string>("McqOpt3")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_3");

                    b.Property<string>("McqOpt4")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("mcq_opt_4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("QuestionsCatalog", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExamTitleId")
                        .HasColumnType("int");

                    b.Property<string>("ExamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FooterNote")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("HeaderNote")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PaperName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SchoolLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SectionMetaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowSectionNames")
                        .HasColumnType("bit");

                    b.Property<string>("SubQuestionNumberingStyle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<bool>("WrapQuestionMarksInParentheses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ExamTitleId");

                    b.HasIndex("SubjectId");

                    b.ToTable("QuestionPaper", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaperQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuestionPaperId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionPaperId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paper_Question");

                    b.HasIndex("QuestionPaperId", "QuestionOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paper_QuestionOrder");

                    b.ToTable("QuestionPaperQuestions", "dbo");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.Chapter", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicClass", "Class")
                        .WithMany("Chapters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_Class");

                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicSubject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Chapters_Subject");

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionCatalog", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Chapter");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaper", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicClass", "Class")
                        .WithMany("QuestionPapers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionPaper_Class");

                    b.HasOne("School.Infrastructure.Academics.Entities.ExamTitle", "ExamTitle")
                        .WithMany("QuestionPapers")
                        .HasForeignKey("ExamTitleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionPaper_ExamTitle");

                    b.HasOne("School.Infrastructure.Academics.Entities.AcademicSubject", "Subject")
                        .WithMany("QuestionPapers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionPaper_Subject");

                    b.Navigation("Class");

                    b.Navigation("ExamTitle");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaperQuestion", b =>
                {
                    b.HasOne("School.Infrastructure.Academics.Entities.QuestionCatalog", "Question")
                        .WithMany("QuestionPaperQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_QPQ_Question");

                    b.HasOne("School.Infrastructure.Academics.Entities.QuestionPaper", "QuestionPaper")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QPQ_Paper");

                    b.Navigation("Question");

                    b.Navigation("QuestionPaper");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicClass", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("QuestionPapers");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.AcademicSubject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("QuestionPapers");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.Chapter", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.ExamTitle", b =>
                {
                    b.Navigation("QuestionPapers");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionCatalog", b =>
                {
                    b.Navigation("QuestionPaperQuestions");
                });

            modelBuilder.Entity("School.Infrastructure.Academics.Entities.QuestionPaper", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
