/**
 * Custom MathLive virtual-keyboard layouts for the question catalog.
 * Stock layouts (numeric, symbols, alphabetic, greek) are kept; Chem + Math are added.
 * Symbols target matric / O-level textbook chemistry and mathematics.
 */

const chemLayout = {
  label: 'Chem',
  tooltip: 'Chemistry',
  rows: [
    [
      { label: 'ce', latex: '\\ce{#0}', class: 'tex' },
      { label: '→', latex: '\\ce{->}', class: 'tex' },
      { label: '⇌', latex: '\\ce{<->}', class: 'tex' },
      { label: '←', latex: '\\ce{<-}', class: 'tex' },
      { label: '→[]', latex: '\\xrightarrow{#0}', class: 'tex small' },
      { label: '→[][]', latex: '\\xrightarrow[#1]{#0}', class: 'tex small' },
      { label: '↑', latex: '\\uparrow', class: 'tex' },
      { label: '↓', latex: '\\downarrow', class: 'tex' },
      { label: '+', latex: '+', class: 'tex' },
    ],
    [
      { label: '(aq)', latex: '\\ce{(aq)}', class: 'small' },
      { label: '(s)', latex: '\\ce{(s)}', class: 'small' },
      { label: '(l)', latex: '\\ce{(l)}', class: 'small' },
      { label: '(g)', latex: '\\ce{(g)}', class: 'small' },
      { label: '—', latex: '-', class: 'tex' },
      { label: '=', latex: '=', class: 'tex' },
      { label: '≡', latex: '\\equiv', class: 'tex' },
      { label: 'Δ', latex: '\\ce{\\Delta}', class: 'tex' },
      { label: 'hν', latex: '\\ce{h\\nu}', class: 'tex small' },
    ],
    [
      { label: '⁺', latex: '^{+}', class: 'tex' },
      { label: '⁻', latex: '^{-}', class: 'tex' },
      { label: '²⁺', latex: '^{2+}', class: 'tex' },
      { label: '²⁻', latex: '^{2-}', class: 'tex' },
      { label: '³⁺', latex: '^{3+}', class: 'tex' },
      { label: 'e⁻', latex: '\\ce{e-}', class: 'tex small' },
      { label: '₁', latex: '_{1}', class: 'tex' },
      { label: '₂', latex: '_{2}', class: 'tex' },
      { label: '₃', latex: '_{3}', class: 'tex' },
      { label: '₄', latex: '_{4}', class: 'tex' },
    ],
    [
      { label: 'H₂O', latex: '\\ce{H2O}', class: 'tex small' },
      { label: 'CO₂', latex: '\\ce{CO2}', class: 'tex small' },
      { label: 'O₂', latex: '\\ce{O2}', class: 'tex small' },
      { label: 'H₂', latex: '\\ce{H2}', class: 'tex small' },
      { label: 'N₂', latex: '\\ce{N2}', class: 'tex small' },
      { label: 'NH₃', latex: '\\ce{NH3}', class: 'tex small' },
      { label: 'HCl', latex: '\\ce{HCl}', class: 'tex small' },
      { label: 'H₂SO₄', latex: '\\ce{H2SO4}', class: 'tex small' },
      { label: 'NaOH', latex: '\\ce{NaOH}', class: 'tex small' },
      { label: 'NaCl', latex: '\\ce{NaCl}', class: 'tex small' },
    ],
    [
      { label: 'CaCO₃', latex: '\\ce{CaCO3}', class: 'tex small' },
      { label: 'CH₄', latex: '\\ce{CH4}', class: 'tex small' },
      { label: 'C₂H₄', latex: '\\ce{C2H4}', class: 'tex small' },
      { label: 'C₂H₂', latex: '\\ce{C2H2}', class: 'tex small' },
      { label: 'C₂H₅OH', latex: '\\ce{C2H5OH}', class: 'tex small' },
      { label: 'CH₃COOH', latex: '\\ce{CH3COOH}', class: 'tex small' },
      '[left]',
      '[right]',
      '[backspace]',
    ],
  ],
}

const mathLayout = {
  label: 'Math',
  tooltip: 'Mathematics',
  rows: [
    [
      { label: 'log□', latex: '\\log_{#0}', class: 'tex' },
      { label: 'log₁₀', latex: '\\log_{10}', class: 'tex small' },
      { label: 'ln', latex: '\\ln', class: 'tex' },
      { label: 'xⁿ', latex: '^{#0}', class: 'tex' },
      { label: 'xₙ', latex: '_{#0}', class: 'tex' },
      { label: 'x²', latex: '^{2}', class: 'tex' },
      { label: 'x³', latex: '^{3}', class: 'tex' },
      { label: '10ⁿ', latex: '10^{#0}', class: 'tex' },
      { label: 'a/b', latex: '\\frac{#?}{#?}', class: 'tex' },
      { label: '√', latex: '\\sqrt{#?}', class: 'tex' },
    ],
    [
      { label: 'ⁿ√', latex: '\\sqrt[#0]{#1}', class: 'tex' },
      { label: '±', latex: '\\pm', class: 'tex' },
      { label: '×', latex: '\\times', class: 'tex' },
      { label: '÷', latex: '\\div', class: 'tex' },
      { label: '·', latex: '\\cdot', class: 'tex' },
      { label: 'π', latex: '\\pi', class: 'tex' },
      { label: 'θ', latex: '\\theta', class: 'tex' },
      { label: '°', latex: '^{\\circ}', class: 'tex' },
      { label: '∞', latex: '\\infty', class: 'tex' },
      { label: '%', latex: '\\%', class: 'tex' },
    ],
    [
      { label: '≤', latex: '\\leq', class: 'tex' },
      { label: '≥', latex: '\\geq', class: 'tex' },
      { label: '≠', latex: '\\neq', class: 'tex' },
      { label: '≈', latex: '\\approx', class: 'tex' },
      { label: '∝', latex: '\\propto', class: 'tex' },
      { label: '~', latex: '\\sim', class: 'tex' },
      { label: '∧', latex: '\\wedge', class: 'tex' },
      { label: '∨', latex: '\\vee', class: 'tex' },
      { label: '→', latex: '\\rightarrow', class: 'tex' },
      { label: '↔', latex: '\\leftrightarrow', class: 'tex' },
      { label: '∈', latex: '\\in', class: 'tex' },
      { label: '∉', latex: '\\notin', class: 'tex' },
      { label: '⊂', latex: '\\subset', class: 'tex' },
    ],
    [
      { label: '⊆', latex: '\\subseteq', class: 'tex' },
      { label: '∪', latex: '\\cup', class: 'tex' },
      { label: '∩', latex: '\\cap', class: 'tex' },
      { label: '∅', latex: '\\varnothing', class: 'tex' },
      { label: '{x|}', latex: '\\{#0\\mid #1\\}', class: 'tex small' },
      { label: 'ℕ', latex: '\\mathbb{N}', class: 'tex' },
      { label: 'ℤ', latex: '\\mathbb{Z}', class: 'tex' },
      { label: 'ℝ', latex: '\\mathbb{R}', class: 'tex' },
      { label: '∠', latex: '\\angle', class: 'tex' },
      { label: '△', latex: '\\triangle', class: 'tex' },
      { label: 'x̄', latex: '\\overline{#0}', class: 'tex' },
      { label: 'm x̄', latex: 'm\\overline{#0}', class: 'tex small' },
    ],
    [
      { label: '⊥', latex: '\\perp', class: 'tex' },
      { label: '∥', latex: '\\parallel', class: 'tex' },
      { label: '∴', latex: '\\therefore', class: 'tex' },
      { label: '∵', latex: '\\because', class: 'tex' },
      { label: 'sin', latex: '\\sin', class: 'tex small' },
      { label: 'cos', latex: '\\cos', class: 'tex small' },
      { label: 'tan', latex: '\\tan', class: 'tex small' },
      { label: '|x|', latex: '\\left|#0\\right|', class: 'tex small' },
      { label: '(', latex: '(', class: 'tex' },
      { label: ')', latex: ')', class: 'tex' },
    ],
    [
      { label: '[', latex: '[', class: 'tex' },
      { label: ']', latex: ']', class: 'tex' },
      { label: 'α', latex: '\\alpha', class: 'tex' },
      { label: 'β', latex: '\\beta', class: 'tex' },
      { label: 'γ', latex: '\\gamma', class: 'tex' },
      { label: 'Δ', latex: '\\Delta', class: 'tex' },
      { label: 'Σ', latex: '\\sum_{#0}^{#1}', class: 'tex' },
      { label: 'lim', latex: '\\lim_{#0}', class: 'tex small' },
      '[left]',
      '[right]',
      '[backspace]',
      '[hide-keyboard]',
    ],
  ],
}

/** Layouts applied while a catalog math-field is focused. */
export const academicQuestionKeyboardLayouts = [
  'numeric',
  'symbols',
  chemLayout,
  mathLayout,
  'alphabetic',
  'greek',
]

export function applyAcademicQuestionKeyboardLayouts() {
  if (typeof window === 'undefined' || !window.mathVirtualKeyboard) return
  window.mathVirtualKeyboard.layouts = academicQuestionKeyboardLayouts
  // Catalog modal uses z-[80]; keep the on-screen keyboard above it.
  document.body.style.setProperty('--keyboard-zindex', '200')
}

export function restoreDefaultKeyboardLayouts() {
  if (typeof window === 'undefined' || !window.mathVirtualKeyboard) return
  window.mathVirtualKeyboard.layouts = 'default'
  document.body.style.removeProperty('--keyboard-zindex')
}

/**
 * Visible Chem / Math insert bar — matric / O-level textbook symbols.
 * Keep labels short; full meaning is in title tooltips.
 */
export const formulaToolbarGroups = [
  {
    id: 'chem',
    label: 'Chem',
    buttons: [
      { id: 'ce', label: 'Chem eq', latex: '\\ce{#0}', title: 'Chemistry equation block' },
      { id: 'arrow', label: '→', latex: '\\ce{->}', title: 'Reaction arrow' },
      { id: 'eqarrow', label: '⇌', latex: '\\ce{<->}', title: 'Equilibrium' },
      { id: 'leftarrow', label: '←', latex: '\\ce{<-}', title: 'Reverse arrow' },
      { id: 'reagent', label: '→[ ]', latex: '\\xrightarrow{#0}', title: 'Arrow with text above — click then type in the box (e.g. A or heat)' },
      { id: 'reagent2', label: '→[][]', latex: '\\xrightarrow[#1]{#0}', title: 'Arrow with text above and below — Tab moves between boxes' },
      { id: 'gasup', label: '↑', latex: '\\uparrow', title: 'Gas evolved' },
      { id: 'pptdown', label: '↓', latex: '\\downarrow', title: 'Precipitate' },
      { id: 'plus', label: '+', latex: '+', title: 'Plus (reactants / products)' },
      { id: 'aq', label: '(aq)', latex: '\\ce{(aq)}', title: 'Aqueous' },
      { id: 'solid', label: '(s)', latex: '\\ce{(s)}', title: 'Solid' },
      { id: 'liquid', label: '(l)', latex: '\\ce{(l)}', title: 'Liquid' },
      { id: 'gas', label: '(g)', latex: '\\ce{(g)}', title: 'Gas' },
      { id: 'bond', label: '—', latex: '-', title: 'Single bond' },
      { id: 'dbond', label: '=', latex: '=', title: 'Double bond' },
      { id: 'tbond', label: '≡', latex: '\\equiv', title: 'Triple bond' },
      { id: 'heat', label: 'Δ', latex: '\\ce{\\Delta}', title: 'Heat' },
      { id: 'light', label: 'hν', latex: '\\ce{h\\nu}', title: 'Light' },
      { id: 'plus1', label: '⁺', latex: '^{+}', title: 'Positive charge' },
      { id: 'minus1', label: '⁻', latex: '^{-}', title: 'Negative charge' },
      { id: 'plus2', label: '²⁺', latex: '^{2+}', title: '2+ charge' },
      { id: 'minus2', label: '²⁻', latex: '^{2-}', title: '2− charge' },
      { id: 'plus3', label: '³⁺', latex: '^{3+}', title: '3+ charge' },
      { id: 'electron', label: 'e⁻', latex: '\\ce{e-}', title: 'Electron' },
      { id: 'sub', label: 'xₙ', latex: '_{#0}', title: 'Subscript — type the number, then Exit script (or →) to continue' },
      { id: 'sup', label: 'xⁿ', latex: '^{#0}', title: 'Superscript — type the power, then Exit script (or →) to continue' },
      { id: 'sub2', label: '₂', latex: '_{2}', title: 'Subscript 2 (caret moves after)' },
      { id: 'sub3', label: '₃', latex: '_{3}', title: 'Subscript 3 (caret moves after)' },
      { id: 'sub4', label: '₄', latex: '_{4}', title: 'Subscript 4 (caret moves after)' },
      { id: 'h2o', label: 'H₂O', latex: '\\ce{H2O}', title: 'Water' },
      { id: 'co2', label: 'CO₂', latex: '\\ce{CO2}', title: 'Carbon dioxide' },
      { id: 'o2', label: 'O₂', latex: '\\ce{O2}', title: 'Oxygen' },
      { id: 'h2', label: 'H₂', latex: '\\ce{H2}', title: 'Hydrogen' },
      { id: 'n2', label: 'N₂', latex: '\\ce{N2}', title: 'Nitrogen' },
      { id: 'nh3', label: 'NH₃', latex: '\\ce{NH3}', title: 'Ammonia' },
      { id: 'hcl', label: 'HCl', latex: '\\ce{HCl}', title: 'Hydrochloric acid' },
      { id: 'h2so4', label: 'H₂SO₄', latex: '\\ce{H2SO4}', title: 'Sulphuric acid' },
      { id: 'naoh', label: 'NaOH', latex: '\\ce{NaOH}', title: 'Sodium hydroxide' },
      { id: 'nacl', label: 'NaCl', latex: '\\ce{NaCl}', title: 'Sodium chloride' },
      { id: 'caco3', label: 'CaCO₃', latex: '\\ce{CaCO3}', title: 'Calcium carbonate' },
      { id: 'ch4', label: 'CH₄', latex: '\\ce{CH4}', title: 'Methane' },
      { id: 'c2h4', label: 'C₂H₄', latex: '\\ce{C2H4}', title: 'Ethene' },
      { id: 'c2h2', label: 'C₂H₂', latex: '\\ce{C2H2}', title: 'Ethyne' },
      { id: 'ethanol', label: 'C₂H₅OH', latex: '\\ce{C2H5OH}', title: 'Ethanol' },
      { id: 'acetic', label: 'CH₃COOH', latex: '\\ce{CH3COOH}', title: 'Ethanoic acid' },
    ],
  },
  {
    id: 'math',
    label: 'Math',
    buttons: [
      { id: 'log', label: 'log□', latex: '\\log_{#0}', title: 'Logarithm with base' },
      { id: 'log10', label: 'log₁₀', latex: '\\log_{10}', title: 'Common log (base 10)' },
      { id: 'ln', label: 'ln', latex: '\\ln', title: 'Natural log' },
      { id: 'pow', label: 'xⁿ', latex: '^{#0}', title: 'Power — type it, then Exit script (or →) to continue' },
      { id: 'subm', label: 'xₙ', latex: '_{#0}', title: 'Subscript — type it, then Exit script (or →) to continue' },
      { id: 'sq', label: 'x²', latex: '^{2}', title: 'Squared (caret moves after)' },
      { id: 'cube', label: 'x³', latex: '^{3}', title: 'Cubed (caret moves after)' },
      { id: 'sci', label: '10ⁿ', latex: '10^{#0}', title: 'Scientific notation' },
      { id: 'frac', label: 'a/b', latex: '\\frac{#?}{#?}', title: 'Fraction — type numerator, then Tab or ↓ for denominator' },
      { id: 'sqrt', label: '√', latex: '\\sqrt{#0}', title: 'Square root' },
      { id: 'nsqrt', label: 'ⁿ√', latex: '\\sqrt[#0]{#1}', title: 'Nth root' },
      { id: 'pm', label: '±', latex: '\\pm', title: 'Plus-minus' },
      { id: 'times', label: '×', latex: '\\times', title: 'Multiply' },
      { id: 'div', label: '÷', latex: '\\div', title: 'Divide' },
      { id: 'cdot', label: '·', latex: '\\cdot', title: 'Dot multiply' },
      { id: 'pi', label: 'π', latex: '\\pi', title: 'Pi' },
      { id: 'theta', label: 'θ', latex: '\\theta', title: 'Theta' },
      { id: 'deg', label: '°', latex: '^{\\circ}', title: 'Degree' },
      { id: 'inf', label: '∞', latex: '\\infty', title: 'Infinity' },
      { id: 'pct', label: '%', latex: '\\%', title: 'Percent' },
      { id: 'leq', label: '≤', latex: '\\leq', title: 'Less or equal' },
      { id: 'geq', label: '≥', latex: '\\geq', title: 'Greater or equal' },
      { id: 'neq', label: '≠', latex: '\\neq', title: 'Not equal' },
      { id: 'approx', label: '≈', latex: '\\approx', title: 'Approximately equal' },
      { id: 'propto', label: '∝', latex: '\\propto', title: 'Proportional to' },
      { id: 'neg', label: '~', latex: '\\sim', title: 'Not / negation (logical)' },
      { id: 'wedge', label: '∧', latex: '\\wedge', title: 'And (logical)' },
      { id: 'vee', label: '∨', latex: '\\vee', title: 'Or (logical)' },
      { id: 'implies', label: '→', latex: '\\rightarrow', title: 'Implies / conditional' },
      { id: 'iff', label: '↔', latex: '\\leftrightarrow', title: 'If and only if / biconditional' },
      { id: 'in', label: '∈', latex: '\\in', title: 'Element of' },
      { id: 'notin', label: '∉', latex: '\\notin', title: 'Not an element of' },
      { id: 'subset', label: '⊂', latex: '\\subset', title: 'Subset' },
      { id: 'subseteq', label: '⊆', latex: '\\subseteq', title: 'Subset or equal' },
      { id: 'cup', label: '∪', latex: '\\cup', title: 'Union' },
      { id: 'cap', label: '∩', latex: '\\cap', title: 'Intersection' },
      { id: 'emptyset', label: '∅', latex: '\\varnothing', title: 'Empty set' },
      { id: 'setbuilder', label: '{x| }', latex: '\\{#0\\mid #1\\}', title: 'Set builder — type the element, then Tab for the condition' },
      { id: 'naturals', label: 'ℕ', latex: '\\mathbb{N}', title: 'Natural numbers' },
      { id: 'integers', label: 'ℤ', latex: '\\mathbb{Z}', title: 'Integers' },
      { id: 'reals', label: 'ℝ', latex: '\\mathbb{R}', title: 'Real numbers' },
      { id: 'angle', label: '∠', latex: '\\angle', title: 'Angle' },
      { id: 'triangle', label: '△', latex: '\\triangle', title: 'Triangle' },
      { id: 'overline', label: 'x̄', latex: '\\overline{#0}', title: 'Line segment bar — type letters (e.g. AB), then Exit script' },
      { id: 'measure', label: 'm x̄', latex: 'm\\overline{#0}', title: 'Measure of a segment — type letters (e.g. AB), then Exit script' },
      { id: 'gt', label: '>', latex: '>', title: 'Greater than' },
      { id: 'lt', label: '<', latex: '<', title: 'Less than' },
      { id: 'perp', label: '⊥', latex: '\\perp', title: 'Perpendicular' },
      { id: 'parallel', label: '∥', latex: '\\parallel', title: 'Parallel' },
      { id: 'therefore', label: '∴', latex: '\\therefore', title: 'Therefore' },
      { id: 'because', label: '∵', latex: '\\because', title: 'Because' },
      { id: 'sin', label: 'sin', latex: '\\sin', title: 'Sine' },
      { id: 'cos', label: 'cos', latex: '\\cos', title: 'Cosine' },
      { id: 'tan', label: 'tan', latex: '\\tan', title: 'Tangent' },
      { id: 'abs', label: '|x|', latex: '\\left|#0\\right|', title: 'Absolute value' },
      { id: 'lparen', label: '(', latex: '(', title: 'Left parenthesis' },
      { id: 'rparen', label: ')', latex: ')', title: 'Right parenthesis' },
      { id: 'alpha', label: 'α', latex: '\\alpha', title: 'Alpha' },
      { id: 'beta', label: 'β', latex: '\\beta', title: 'Beta' },
      { id: 'gamma', label: 'γ', latex: '\\gamma', title: 'Gamma' },
      { id: 'delta', label: 'Δ', latex: '\\Delta', title: 'Delta' },
      { id: 'sum', label: 'Σ', latex: '\\sum_{#0}^{#1}', title: 'Summation' },
      { id: 'lim', label: 'lim', latex: '\\lim_{#0}', title: 'Limit' },
    ],
  },
]
